language: ruby
sudo: false
cache: bundler
rvm:
- 2.4
- 2.5
- 2.6
gemfile:
- gemfiles/rails3.2.gemfile
- gemfiles/rails4.2.gemfile
- gemfiles/rails5.0.gemfile
- gemfiles/rails5.1.gemfile
- gemfiles/rails5.2.gemfile
- gemfiles/rails6.0.gemfile
branches:
  only: master
before_install: gem update --system >/dev/null && gem install matching_bundle -v ">= 0.3.2" --no-doc && matching_bundle install
script: matching_bundle exec rake $TASK
env:
- TASK=default
matrix:
  exclude:
  - rvm: 2.4
    gemfile: gemfiles/rails6.0.gemfile
  - rvm: 2.5
    gemfile: gemfiles/rails4.2.gemfile
  - rvm: 2.5
    gemfile: gemfiles/rails3.2.gemfile
  - rvm: 2.6
    gemfile: gemfiles/rails4.2.gemfile
  include:
  - rvm: 2.4 # lowest ruby version
    env: TASK=rubocop
  # TODO: fix weird rails testing errors unrelated to the library
  allow_failures:
  - rvm: 2.5
    gemfile: gemfiles/rails6.0.gemfile
  - rvm: 2.6
    gemfile: gemfiles/rails6.0.gemfile
